spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: true
  redis:
    database: 0
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  mail:
    host: smtp.163.com
    username: aufecomPan@163.com
    password: JJTXHCBJRXJWWDNR
    protocol: smtps
    properties:
      mail:
        stmp:
          ssl:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

community:
  path:
    domain: http://localhost:8080
    upload: /Users/Pan/Desktop/upload  # 后面改用七牛云了
server:
  port: 8080
  servlet:
    context-path: /community

elasticsearch:
  host: localhost
  port: 9200

qiniu:
  key:
    access: HRHcKAGXeZ0SeJP5Xy01KFmp4R_3mSkC_35hIB3H
    secret: E6pf1RgEZReEzibcw4SHF-Oz3o3bsAVYYg2EZEGt
  bucket:
    header:
      name: mini-community-headurl
      url: http://rb5apblqg.hd-bkt.clouddn.com

caffeine:
  posts:
    max-size: 15
    expire-seconds: 180

management:
  endpoints:
    web:
      exposure:
        include: beans, health, database
        exclude: info, caches



